FROM node:16-alpine3.14

WORKDIR /app

# copy configs to /app folder
COPY package*.json ./

ARG NODE_ENV
RUN if [ "${NODE_ENV}" = "development" ]; \
        then npm install --also=dev; \
        else npm install --only=production; \
        fi

# copy source code to /app/src folder
COPY . .

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

RUN npm run build

EXPOSE 7777

CMD [ "npm", "run", "dev" ]