FROM node:16-alpine3.14

WORKDIR /app

# copy configs to /app folder
COPY package*.json ./

ARG NODE_ENV
RUN npm install --also=dev;

# copy source code to /app/src folder
COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]