FROM node:16-alpine3.14 as build

ARG REACT_APP_SERVICES_HOST=/api/v1
ARG REACT_APP_SOCKET_URL
WORKDIR /app

# copy configs to /app folder
COPY package*.json ./


RUN npm install --only=production;

# copy source code to /app/src folder
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
