version: '3'
services:
  api: 
    build:
      dockerfile: dockerfile.prod
      args:
        NODE_ENV: "production"
  client:
    build: 
      dockerfile: dockerfile.prod
      context: ./client
    volumes:
      - ./client:/app

    

