version: '3.8'

services:   
  api:
    image: nginx-api
    build :
      context: ./crawler
    restart : unless-stopped
    env_file:
      - ./.env
    volumes:
        - /app/node_modules
    networks:
      - backend
    depends_on:
      - redis-server
    ports:
      - "6001:6001"
      - "5000:5000"
  client :
    image : nginx-frontend
    build: 
      context: ./client
      args:
        - REACT_APP_SERVICES_HOST=/api/v1
    ports:
      - "80:80"
    depends_on:
      - api
    restart : unless-stopped
    volumes:
      - /app/node_modules
    env_file:
      - ./.env
    networks:
      - frontend
      - backend

  redis-server:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6300"]
    networks:
      - backend
networks:
  frontend:
  backend:
    driver: bridge