version: '3.8'

services:   
  api:
    depends_on:
      - redis
    build :
      context: ./crawler
    restart : unless-stopped
    env_file:
      - ./.env
    volumes:
        - /app/node_modules
  client :
    stdin_open: true
    depends_on:
      - api
    restart : unless-stopped
    build: 
      context: ./client
      args:
         - REACT_APP_SOCKET_URL=http://127.0.0.1:5000
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
    env_file:
      - ./.env
        
  redis:
    image: redis:latest
    deploy:
      replicas: 1
  nginx :
    depends_on:
      - api
      - client
    restart : always
    build : 
      context : ./nginx
    ports:
      - "3050 :80"
  
