version: '3'
services:
  api: 
    build:
      args:
        NODE_ENV: "development"
    volumes:
      -./crawler:/app
    command: npm run dev
  client:
    build: 
      dockerfile: dockerfile
      context: ./client
    volumes:
      -./client:/app

    

