# Our first stage, that is the Builder
FROM node:16-alpine3.14 as ts-compiler
WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
RUN npm install
COPY . ./
RUN npm run clean
RUN npm run build



# Our Second stage, that creates an image for production
FROM node:16-alpine3.14 AS ts-sample-prod
WORKDIR /app
COPY --from=ts-compiler ./app/dist ./dist
COPY package* ./
RUN npm install --production
CMD npm start


