FROM node:16-alpine3.14

# update packages
RUN apk update
# create root application folder
WORKDIR /app

# copy configs to /app folder
COPY package*.json ./
COPY tsconfig.json ./
# copy source code to /app/src folder
COPY src /app/src

# check files list
RUN ls -a
ARG NODE_ENV=production
RUN if [ "${NODE_ENV}" = "development" ]; \
        then npm install --also=dev; \
        else npm install --only=production; \
        fi

COPY . . 

RUN if [ "${NODE_ENV}" = "production" ]; \
        then npm run build \
        fi